const wdArray=[
    {
        model:"8450",
        maker:"Wayne Dalton",
        panel_style:"Frameless",
        product_family:"Full-View Aluminum",
        door_style_text:"Full-View",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"https://www.wayne-dalton.com/Documents/aluminum-glass-garage-door-8450-brochure.pdf",
        price:"$$$$$",
        r_value_text:"",
        rtm_construction_type:'2" Thick - NonInsulated Alumnium Rails',
        rtm_insulation_type:"",
        section_material:"Heavy Duty / Aluminum",
        url:"https://www.wayne-dalton.com/aluminum-glass-garage-doors-8450",
        image:["https://www.wayne-dalton.com/DoorImages/8450-Luminous-Opaque-White.jpg","https://www.wayne-dalton.com/DoorDesigns/8450-aluminum-16x7-exterior-view.jpg","https://www.wayne-dalton.com/DoorImages/8450-Luminous-Translucent-Black-ResAlumCollection.jpg"],
        warranty:"https://www.wayne-dalton.com/Documents/aluminum-model-8450-8850-451-452-464-warranty.pdf"
    },
    {
        model:"8800",
        maker:"Wayne Dalton",
        panel_style:"Full-View",
        product_family:"Full-View Aluminum",
        door_style_text:"Full-View (Western US ONLY)",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"https://www.wayne-dalton.com/Documents/garage-door-model-8800-brochure.pdf",
        price:"$$$$$",
        r_value_text:"3.02-4.36",
        rtm_construction_type:'2" Thick , Insulated/Non Insulated Aluminum Rails',
        rtm_insulation_type:"Polyurethane",
        section_material:"Heavy Duty / Aluminum",
        url:"https://www.wayne-dalton.com/aluminum-glass-garage-doors-8800",
        image:["https://www.wayne-dalton.com/og/Aluminim-Garage-Door-8800-Black-White-Laminated-DESK.jpg","https://www.wayne-dalton.com/DoorDesigns/8800-aluminum-glass-over-12-ft-wide-4-panel-3-in-frame.JPG","https://www.wayne-dalton.com/DoorDesigns/8800-aluminum-glass-over-12-ft-wide-4-panel-6-in-frame.JPG"],
        warranty:"https://www.wayne-dalton.com/Documents/garage-door-model-8800-warranty.pdf"
    },
    {
        model:"8850",
        maker:"Wayne dalton",
        panel_style:"Full-View",
        product_family:"Full-View Aluminum",
        door_style_text:"Full-View (Eastern US ONLY)",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"https://www.wayne-dalton.com/Documents/garage-door-model-8850-brochure.pdf",
        price:"$$$$",
        r_value_text:"2.74-4.06",
        rtm_construction_type:'2" Thick , Insulated/Non Insulated Aluminum Rails',
        rtm_insulation_type:"Polyurethane",
        section_material:"Heavy Duty/Aluminum",
        url:"https://www.wayne-dalton.com/aluminum-glass-garage-doors-8850",
        image:["https://www.wayne-dalton.com/DoorImages/8850-Aluminum-PowderCoat-Black-SatinEtch.jpg","https://www.wayne-dalton.com/cards/aluminum-garage-door-8850.jpg","https://www.wayne-dalton.com/DoorDesigns/8850-aluminum-glass-7Hx16W-4panels.jpg"],
        warranty:"https://www.wayne-dalton.com/Documents/aluminum-model-8450-8850-451-452-464-warranty.pdf"
    },
    {
        model:"9800",
        maker:"Wayne Dalton",
        panel_style:"Fiberglass",
        product_family:"High-Definition Fiberglass",
        door_style_text:"Fiberglass",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"https://www.wayne-dalton.com/Documents/garage-door-model-9800-brochure.pdf",
        price:"$$$$$",
        r_value_text:"7.6",
        rtm_construction_type:'2" Thick - 2-Sided Fiberglass and Steel',
        rtm_insulation_type:"Polyurethane",
        section_material:"Designer Fiberglass",
        url:"https://www.wayne-dalton.com/fiberglass-garage-doors-9800",
        image:["https://www.wayne-dalton.com/DoorImages/9800-Fiberglass-Garage-Door-Horiz-Raised-Panel-Walnut.jpg","https://www.wayne-dalton.com/cards/fiberglass-garage-door-9800.jpg","https://www.wayne-dalton.com/DoorDesigns/9800-horizontal-groove-7ft.jpg"],
        warranty:"https://www.wayne-dalton.com/Documents/garage-door-model-9800-warranty.pdf"
    },
    {
        model:"8700",
        maker:"Wayne Dalton",
        panel_style:"Shaker",
        product_family:"Vinyl",
        door_style_text:"Shaker",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"https://www.wayne-dalton.com/Documents/garage-door-model-8700-brochure.pdf",
        price:"$$",
        r_value_text:"11.75",
        rtm_construction_type:"",
        rtm_insulation_type:"Polyurethane",
        section_material:"Vinyl Skin around Insulation, Steel Stiles/Rails",
        url:"https://www.wayne-dalton.com/vinyl-garage-doors-8700",
        image:["https://www.wayne-dalton.com/cards/vinyl-garage-door-8700.jpg"],
        warranty:"https://www.wayne-dalton.com/Documents/garage-door-model-8700-warranty.pdf"
    },
    {
        model:"9700",
        maker:"Wayne Dalton",
        panel_style:"Carriage",
        product_family:"Carriage Steel",
        door_style_text:"Carriage",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"https://www.wayne-dalton.com/Documents/garage-door-model-9700-brochure.pdf",
        price:"$$$",
        r_value_text:"10",
        rtm_construction_type:'2" Thick - 2-Sided Steel',
        rtm_insulation_type:"Polyurethane",
        section_material:"Medium Duty / Steel",
        url:"https://www.wayne-dalton.com/carriage-house-steel-garage-doors-9700",
        image:["https://www.wayne-dalton.com/DoorImages/9700-CH-Garage-Door-Bellview-Custom-Paint-24-Window-Square.jpg","https://www.wayne-dalton.com/cards/carriagehouse-steel-garage-door-9700.jpg"],
        warranty:"https://www.wayne-dalton.com/Documents/garage-door-model-9700-warranty.pdf"
    },
    {
        model:"6600",
        maker:"Wayne Dalton",
        panel_style:"Overlay",
        product_family:"Overlay Carriage House",
        door_style_text:"Overlay",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"https://www.wayne-dalton.com/Documents/garage-door-model-6600-brochure.pdf",
        price:"$$$$",
        r_value_text:"12.12",
        rtm_construction_type:"Decatrim Overlay / 2- Sided Steel",
        rtm_insulation_type:"Polyurethane",
        section_material:"Medium Duty Steel",
        url:"https://www.wayne-dalton.com/carriage-house-steel-garage-doors-6600",
        image:["https://www.wayne-dalton.com/cards/carriagehouse-steel-garage-door-6600.jpg","https://www.wayne-dalton.com/DoorDesigns/6600-arch-brunswick-panel.jpg","https://www.wayne-dalton.com/DoorDesigns/6600-arch-lexington-panel.jpg"],
        warranty:"https://www.wayne-dalton.com/Documents/garage-door-model-6600-warranty.pdf"
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    {
        model:"",
        maker:"",
        panel_style:"",
        product_family:"",
        door_style_text:"",
        family_brochure_link:"https://www.wayne-dalton.com/Documents/Misc%20Brochures/residential-garage-door-catalog.pdf",
        model_flyer_link:"",
        price:"",
        r_value_text:"",
        rtm_construction_type:"",
        rtm_insulation_type:"",
        section_material:"",
        url:"",
        image:[],
        warranty:""
    },
    
    
    
]